name = "rendertron-lite"
main = "src/index.js"
compatibility_date = "2025-08-13"
compatibility_flags = ["nodejs_compat"]
account_id = "c6af148bcfb547ae1e1386dcd8de8dc5"

[browser]
binding = "MYBROWSER"

[vars]
AI_ENDPOINT = "https://api.openai.com/v1/responses"
AI_TIMEOUT_MS = "240000"          # faster cycles; adjust if needed
OPENAI_MODEL = "gpt-5"     # ⚡ fast + vision-capable

[[kv_namespaces]]
binding = "KV_CACHE"
id = "rendertron-cache"